version: '3.7'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  liferay:
    image: liferay/portal:7.4.3.132-ga132
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://mysql:3306/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: liferay
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: liferay
      LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED: "false"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - liferay_data:/opt/liferay/data

volumes:
  mysql_data:
  liferay_data: