admin.email.from.address=topthietke.com@gmail.com
admin.email.from.name=Test Test
company.default.locale=en_US
company.default.time.zone=UTC
company.default.web.id=gmail.com
default.admin.email.address.prefix=topthietke.com
liferay.home=D:/Du_an/File/Test/liferays/LiferayCE7.4
setup.wizard.enabled=false
